{{- if not .Values.roleBindings.controller.existingRoleBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: nx-cloud-workflow-controller-rolebinding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nx-cloud-workflow-controller-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccounts.controller.name }}
    namespace: {{ .Values.global.namespace }}
{{- end }}
{{- if not .Values.roleBindings.runner.existingRoleBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: nx-cloud-workflow-runner-rolebinding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nx-cloud-workflow-runner-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.runner.name }}
  namespace: {{ .Values.global.namespace }}
{{- end }}