{{- if .Values.enableMessageQueue }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-cloud-messagequeue
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nx-cloud-messagequeue
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nx-cloud-messagequeue
  template:
    metadata:
      labels:
        app: nx-cloud-messagequeue
    spec:
      {{- if .Values.messagequeue.serviceAccountName }}
      serviceAccountName: {{ .Values.messagequeue.serviceAccountName }}
      {{- end }}
      containers:
        - name: nx-cloud-messagequeue
          image: {{ include "nxCloud.images.messagequeue.image" . }}
          imagePullPolicy: {{ .Values.messagequeue.image.pullPolicy | quote }}
          {{- if .Values.messagequeue.resources }}
          resources: {{- toYaml .Values.messagequeue.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.messagequeue.deployment.env }}
            {{- toYaml .Values.messagequeue.deployment.env | nindent 12 }}
            {{- else }}
            - name: ACTIVEMQ_TMP
              value: /opt/activemq/tmp
            {{- end }}
          ports:
            - containerPort: {{ .Values.messagequeue.deployment.port }}
              name: tcp
          {{- if .Values.messagequeue.securityContext }}
          securityContext:
          {{- toYaml .Values.messagequeue.securityContext | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.messagequeue.deployment.volumeMounts }}
            {{- toYaml .Values.messagequeue.deployment.volumeMounts | nindent 12 }}
            {{- else }}
            - mountPath: /opt/activemq/data
              name: data
            - mountPath: /opt/activemq/tmp
              name: tmp
            {{- end }}
      volumes:
        {{- if .Values.messagequeue.deployment.volumes }}
        {{- toYaml .Values.messagequeue.deployment.volumes | nindent 8 }}
        {{- else }}
        - emptyDir: { }
          name: data
        - emptyDir: { }
          name: tmp
        {{- end }}
{{- end }}