{{- if and (not .Values.awsS3.enabled) (not .Values.azure.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-volume
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  {{- if .Values.fileStorage.resourcePolicy }}
  annotations:
    helm.sh/resource-policy: {{ .Values.fileStorage.resourcePolicy | quote }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.fileStorage.storageClassName }}
  storageClassName: {{ .Values.fileStorage.storageClassName }}
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.fileStorage.size }}
{{- end }}